### ISSUE TITLE
关于LCSTS测rouge的问题

### ISSUE THREAD

**Issue by travel-go** [lancopku/Global-Encoding#11]
你好：我想请教一下关于LCSTS的word-based和character-based测rouge的问题。举个例子:
训练结果：上 市 公 司 朋 友 圈 合 作 背 后 利 益 均 沾
实际结果：揭 秘 “ 老 虎 们 ” 的 上 市 公 司 朋 友 圈 合 作 背 后 利 益 均 沾
是直接用 files2rouge测两者之间的rouge么？ 还是需要改变什么，比如说将中文字改成数字之类的，或者需要其他的改变。
谢谢！

**Comment by JustinLin610** [comment]
改成数字了，然后可以用这里提供的pyrouge测。

**Comment by travel-go** [comment]
好的谢谢

**Comment by jiahuanluo** [comment]
你好。我想请教一下，论文上的Rouge Score是，用pyrouge.Rouge155()的默认参数还是设置了其他参数？比如rouge_args='-m -b 75 -n 2 -w 1.2 -e {} -a'.format(ROUGE_PATH)？

**Comment by JustinLin610** [comment]
一般用默认，我们自己测DUC的测试集的时候用了你说的这个
