### ISSUE TITLE
关于Gigaword dataset的问题。

### ISSUE THREAD

**Issue by jiahuanluo** [lancopku/Global-Encoding#12]
关于Gigaword dataset的问题，论文中提到，你们用的是Rush et al. (2015)处理好的数据。我想问一下这个数据在哪里可以找到？我去Rush et al. (2015)找了，找不到。关于源数据，我给LDC写了申请，也没有回复。所以我想问一下你们，这个数据怎么获取的。非常感谢你们的工作！

**Comment by JustinLin610** [comment]
去harvardnlp那儿下就行

**Comment by jiahuanluo** [comment]
非常感谢林大佬的回复。谢谢你们的工作~
