### ISSUE TITLE
problem when beam is 1

### ISSUE THREAD

**Issue by ZHANG45** [lancopku/Global-Encoding#16]
When beam is 1, candidate likes [None, None, None...], and causes error, because you didn't transform tensor "samples(line 207 of train.py)"  into list.
You can change line 86 of seq2seq.py like this to solve this problem
`sample_ids = torch.index_select(outputs, dim=1, index=reverse_indices).t().tolist()`

**Comment by JustinLin610** [comment]
You're right, and thanks a lot for your suggestion. This is because the original sample_ids become tensor in this version.
