### ISSUE TITLE
评估矩阵为空

### ISSUE THREAD

**Issue by loongriver** [lancopku/Global-Encoding#17]
Traceback (most recent call last):
  File "train.py", line 322, in <module>
    main()
  File "train.py", line 316, in main
    print_log("Best %s score: %.2f\n" % (metric, max(params[metric])))

**Comment by JustinLin610** [comment]
有没有更加具体点的报错？没见过这种情况

**Comment by duguiming111** [comment]
我也遇到了这个情况，但不调试看到，params[metric]为一个空列表。

**Comment by duguiming111** [comment]
请问，print_log("Best %s score: %.2f\n" % (metric, max(params[metric])))，这个paramas[metric]应该是列表里面是元组，元组里面又是三个列表，我到这里求最大值出错了，是我哪里整错了吗？

**Comment by lizhzh8** [comment]
这个问题解决了吗？

**Comment by JustinLin610** [comment]
正常的print log应该没有问题的，应该是max那部分有点问题。我检查下然后尽快更新
