### ISSUE TITLE
关于中文是否需要分词

### ISSUE THREAD

**Issue by chenjun0210** [lancopku/Global-Encoding#18]
请教几个问题，
一，你们中文跑的粒度是词粒度还是字符粒度呀，哪种效果好呢？
二，原始数据要做预处理，比如去掉标点符号啥的。
三，这个方法你们有在标题生成任务测过吗

我的程序还在跑目前先用的char，跑了好久一直没有loss日志输出来，不知道为啥，是要跑很久才能看到loss输出吗？我用的数据量也不大，nlpcc2017摘要数据试的

**Comment by JustinLin610** [comment]
用的字粒度的。loss的话应该不用等很久的

**Comment by xiaozhi2015** [comment]
输入格式能给个示例么，带不带标点，加不加空格？ @chenjun0210  Muck thx!
