### ISSUE TITLE
Doubt on some pieces of code

### ISSUE THREAD

**Issue by Thidtc** [lancopku/Global-Encoding#2]
* in function sortFinished in models/beam.py, when the parameter minimum is not None, we need add from beam, but during the iteration, the beam index i is not updated
```
if minimum is not None:
  i = 0
  # Add from beam until we have minimum outputs.
  while len(self.finished) < minimum:
    s = self.scores[i]
    self.finished.append((s, len(self.nextYs) - 1, i))
    # update i?
    # i += 1
```

* in function sample in models.seq2seq.py line 125, is the variable alignmentsi misspelled?

**Comment by JustinLin610** [comment]
Many thanks for pointing out our mistakes. We've already corrected them.

**Comment by dragon558** [comment]
hello，谢谢作者的开源分享．有几点疑问想向您请教下：１.我看代码inception部分，BN放在conv和RELU后面而不是二者中间，请问这个是有什么特别的考量么？2.self-attention部分的操作和大众所知的self-attention貌似也有一些差别，也有特殊考量么？3.GLU部分，是用LSTM的正向output＊sigmoid(反向output)，有木有考虑过直接［正向，反向］＊sigmoid([正向，反向])呢？
