### ISSUE TITLE
代码错误的地方: beam_search

### ISSUE THREAD

**Issue by sys1874** [lancopku/Global-Encoding#3]
错误的代码：
 def unbottle(m):
            return m.view(beam_size, batch_size, -1)
修改后：
def unbottle(m):
            return m.view(batch_size, beam_size, -1)

**Comment by JustinLin610** [comment]
It works on each batch individually. Please see L162 as well beam.py.

**Comment by sys1874** [comment]
inp = var(torch.stack([b.getCurrentState() for b in beam])
                      .t().contiguous().view(-1))
**inp的格式： batch_size X beam_size**

output, decState, attn, memory = self.decoder(inp, decState, embeds, memory)

**output的格式： batch_size*beam_size  X vocab_size**

output = unbottle(self.log_softmax(output))

**unbottle 变成： beam_size X batch_size  X vocab_size**
怎么突然就变成了beam_size优先了？

**Comment by JustinLin610** [comment]
The size of the input is dependent on the decoder, while the size of the output for beam search is dependent on the implementation of beam search. This is why I advised you to check beam.py, especially the "advance" function. I think if you really prefer "batch size first", you can also make some changes on your implementation of beam :)
