### ISSUE TITLE
关于rouge测试

### ISSUE THREAD

**Issue by sys1874** [lancopku/Global-Encoding#4]
你好，在测试中文摘要的时候，会遇到如下报错：
Illegal division by zero at /home/zhumaokun/ROUGE/RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450.

是不是该对中文转换成英文字符？？

**Comment by sys1874** [comment]
中文测试是使用 PythonROUGE.py 这个模板？
英文测试使用 metrics.py 这个模板？

**Comment by JustinLin610** [comment]
Hi, 你用英文的会有错吗？中英文都是用pyrouge，写在metrics.py里面，train.py会进行调用。

我偶尔会碰到这个问题，一般是因为有长度为0的句子或者有非法字符，你可以检查下有没有</s>，</t>之类的。我在某些数据集上因为类似字符出过这个问题。做LCSTS的时候我们的数据集都先把每个汉字转化成数字才送进去的，句子就变成了数字序列，因此不存在这个问题，你也可以考虑试下。

**Comment by sys1874** [comment]
谢谢你的建议，我把汉语字符转化成数字训练在用pyrouge测试时，就可以避免这个问题了。
但是使用metrics.py去测试LCSTS数据中的实验数据sumary.generated.char.context.txt  和 sumary.human.txt。
测试得到的结果和给出的结果有些许差别。  造成的原因是参数设置不同吗？

**测试结果：**
---------------------------------------------
1 ROUGE-1 Average_R: 0.33984 (95%-conf.int. 0.32653 - 0.35323)
1 ROUGE-1 Average_P: 0.27891 (95%-conf.int. 0.26780 - 0.29069)
1 ROUGE-1 Average_F: 0.29250 (95%-conf.int. 0.28207 - 0.30341)
---------------------------------------------
1 ROUGE-2 Average_R: 0.19986 (95%-conf.int. 0.18844 - 0.21124)
1 ROUGE-2 Average_P: 0.16059 (95%-conf.int. 0.15088 - 0.17023)
1 ROUGE-2 Average_F: 0.16915 (95%-conf.int. 0.15963 - 0.17845)
---------------------------------------------
1 ROUGE-3 Average_R: 0.11313 (95%-conf.int. 0.10328 - 0.12296)
1 ROUGE-3 Average_P: 0.08897 (95%-conf.int. 0.08072 - 0.09717)
1 ROUGE-3 Average_F: 0.09422 (95%-conf.int. 0.08586 - 0.10245)
---------------------------------------------
1 ROUGE-4 Average_R: 0.06934 (95%-conf.int. 0.06111 - 0.07774)
1 ROUGE-4 Average_P: 0.05271 (95%-conf.int. 0.04606 - 0.05984)
1 ROUGE-4 Average_F: 0.05636 (95%-conf.int. 0.04978 - 0.06355)
---------------------------------------------
1 ROUGE-L Average_R: 0.30950 (95%-conf.int. 0.29675 - 0.32269)
1 ROUGE-L Average_P: 0.25393 (95%-conf.int. 0.24304 - 0.26558)
1 ROUGE-L Average_F: 0.26624 (95%-conf.int. 0.25562 - 0.27680)
---------------------------------------------
**LCSTS给出的结果：**
---------------------------------------------
1 ROUGE-1 Average_R: 0.35477 (95%-conf.int. 0.34076 - 0.36873)
1 ROUGE-1 Average_P: 0.27947 (95%-conf.int. 0.26828 - 0.29130)
1 ROUGE-1 Average_F: 0.29919 (95%-conf.int. 0.28842 - 0.31055)
---------------------------------------------
1 ROUGE-2 Average_R: 0.21025 (95%-conf.int. 0.19800 - 0.22271)
1 ROUGE-2 Average_P: 0.16183 (95%-conf.int. 0.15211 - 0.17154)
1 ROUGE-2 Average_F: 0.17420 (95%-conf.int. 0.16437 - 0.18403)
---------------------------------------------
1 ROUGE-3 Average_R: 0.12019 (95%-conf.int. 0.10992 - 0.13098)
1 ROUGE-3 Average_P: 0.09045 (95%-conf.int. 0.08218 - 0.09899)
1 ROUGE-3 Average_F: 0.09794 (95%-conf.int. 0.08948 - 0.10662)
---------------------------------------------
1 ROUGE-4 Average_R: 0.07434 (95%-conf.int. 0.06588 - 0.08362)
1 ROUGE-4 Average_P: 0.05399 (95%-conf.int. 0.04731 - 0.06108)
1 ROUGE-4 Average_F: 0.05905 (95%-conf.int. 0.05224 - 0.06654)
---------------------------------------------
1 ROUGE-L Average_R: 0.32301 (95%-conf.int. 0.30934 - 0.33620)
1 ROUGE-L Average_P: 0.25442 (95%-conf.int. 0.24332 - 0.26617)
1 ROUGE-L Average_F: 0.27231 (95%-conf.int. 0.26135 - 0.28315)

**Comment by JustinLin610** [comment]
这两个txt都是LCTST那边提供的？pyrouge调用的是ROUGE-1.5.5，估计可能是rouge有些参数的问题吧，不太清楚。但我看F值差异不算很大，就是pyrouge的分数稍低一些

**Comment by jiahuanluo** [comment]
@sys1874 你好，我在测试giga数据集的时候，也会出现Illegal division by zero at /root/RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450。请问这个该怎么办呢？

**Comment by Kaijie234** [comment]
@JustinLin610  您好，我在测试LCSTS数据集时也遇到这个问题，您说的汉语字符转成数字，具体应该如何操作？
total number of parameters: 83289940

 [========================================= 10000/10000 ===============================>]  Step: 100ms | Tot: 16m55s                      
epoch:   1, loss: 890.659, time: 1031.758, updates:    10000, accuracy: 99.10
evaluating after 10000 updates...
Illegal division by zero at Global-Encoding-master/RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450. Step: 634ms | Tot: 0ms                         
Traceback (most recent call last):
  File "Global-Encoding-master/train.py", line 323, in <module>
    main()
  File "Global-Encoding-master/train.py", line 315, in main
    train_model(model, data, optim, i, params)
  File "Global-Encoding-master/train.py", line 172, in train_model
    score = eval_model(model, data, params)
  File "Global-Encoding-master/train.py", line 243, in eval_model
    score[metric] = getattr(utils, metric)(reference, candidate, params['log_path'], params['log'], config)
  File "/home/gkj/Global-Encoding-master/utils/metrics.py", line 58, in rouge
    rouge_results = r.convert_and_evaluate()
  File "/home/gkj/anaconda3/envs/pytorch04/lib/python3.5/site-packages/pyrouge/Rouge155.py", line 361, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/home/gkj/anaconda3/envs/pytorch04/lib/python3.5/site-packages/pyrouge/Rouge155.py", line 336, in evaluate
    rouge_output = check_output(command).decode("UTF-8")
  File "/home/gkj/anaconda3/envs/pytorch04/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/home/gkj/anaconda3/envs/pytorch04/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['Global-Encoding-master/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', 'Global-Encoding-master/RELEASE-1.5.5/data', '-c', '95', '-2', '-1', '-U', '-r', '1000', '-n', '4', '-w', '1.2', '-a', '-m', '/tmp/tmpcgwo9awp/rouge_conf.xml']' returned non-zero exit status 255

**Comment by 2efPer** [comment]
每个汉字转化成数字才送进去的话，那数字怎么办？
