### ISSUE TITLE
关于论文中的model的字典大小

### ISSUE THREAD

**Issue by sys1874** [lancopku/Global-Encoding#5]
请问一下，你在论文中model使用的字典大小是5W吗？

打算做对比实验，想设定baseline model一样的参数，但是发现字典大小没有给。。。

**Comment by JustinLin610** [comment]
Giga?

**Comment by sys1874** [comment]
LCSTS 关于 char  和 word  两种情况的.

**Comment by JustinLin610** [comment]
我LCSTS都用字级别的数据，没有做词级别的，用了4000个汉字

**Comment by sys1874** [comment]
好的,谢谢。
