### ISSUE TITLE
关于giaword的字典

### ISSUE THREAD

**Issue by sys1874** [lancopku/Global-Encoding#6]
同学，你好，打扰了。
想问问你， 关于 giaword 你是取全部单词当作字典大小吗？   还是高频词前5W个？

**Comment by JustinLin610** [comment]
我用的5w

**Comment by sys1874** [comment]
好的，谢谢

**Comment by jiahuanluo** [comment]
@sys1874 同学你好！打扰了。想问问你，关于gigaword的数据集，你是直接用https://github.com/harvardnlp/sent-summary 这个吗？还是另外获取的？谢谢！
