### ISSUE TITLE
ROUGE计算的时候报错 non-zero exit status 2

### ISSUE THREAD

**Issue by kinghuin** [lancopku/Global-Encoding#7]
我用的是srush 的数据集

“Training and evaluation data for Gigaword is available https://drive.google.com/open?id=0B6N7tANPyVeBNmlSX19Ld2xDU1E”

我将下载的文件命名为train.src, train.tgt, valid.src, valid.tgt, test.src and test.tgt后放入 giga文件夹中，并在这个giga文件夹中新建了一个data空文件夹。

之后运行 python3 preprocess.py -load_data giga -save_data newgiga

再之后 将giga_yam中的data 改成 ‘newgiga/’

模型成功训练，与验证，但验证完毕开始计算rouge分数的时候，

显示

Command '['script/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', 'script/RELEASE-1.5.5/data', '-c', '95', '-2', '-1', '-U', '-r', '1000', '-n', '4', '-w', '1.2', '-a', '-m', '/tmp/tmp6fmy4hlt/rouge_conf.xml']' returned non-zero exit status 2

我尝试了 
https://github.com/tagucci/pythonrouge/issues/11中提到的方法：

“
cd pythonrouge/RELEASE-1.5.5/data/
rm WordNet-2.0.exc.db
./WordNet-2.0-Exceptions/buildExeptionDB.pl ./WordNet-2.0-Exceptions ./smart_common_words.txt ./WordNet-2.0.exc.db
”

均无法解决这个问题，请问应该怎么做呢？

**Comment by JustinLin610** [comment]
不太有印象这个问题，你看看把RELEASE那个包放在你的用户根目录下，然后再设置pyrouge的路径，你看看能不能解决。

**Comment by Tambura** [comment]
出现该错误的原因是有一些perl的模块没安装，将Command '['script/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', 'script/RELEASE-1.5.5/data', '-c', '95', '-2', '-1', '-U', '-r', '1000', '-n', '4', '-w', '1.2', '-a', '-m', '/tmp/tmp6fmy4hlt/rouge_conf.xml']'  这个命令直接在终端执行以下，会提示你缺少哪些模块。

使用cpanm安装缺少的perl module.

**Comment by jiahuanluo** [comment]
@wherebubugs 你好。你这个问题解决了吗？我按照 @Tambura 的方法解决了这个问题，之后又出现了另外一个问题
Illegal division by zero at /root/RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450
我也是跑你的这个数据，你有遇到这个问题吗？

**Comment by kinghuin** [comment]
@jiahuanluo 我没有再尝试这个方案了，改用了Files2ROUGE或者pythonrouge

**Comment by JustinLin610** [comment]
把更新了的代码里面的RELEASE-1.5.5放到home下然后再set rouge path，或者直接修改对它的权限，这样pyrouge的使用应该就没有问题。division by zero一般的情况是有空行或者是非法字符

**Comment by jiahuanluo** [comment]
> 把更新了的代码里面的RELEASE-1.5.5放到home下然后再set rouge path，或者直接修改对它的权限，这样pyrouge的使用应该就没有问题。division by zero一般的情况是有空行或者是非法字符

Illegal division by zero at /root/RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450
我这个问题是因为有非法字符，我把utils/metrics.py里面的第49行后面加上.replace('<unk>', 'UNK')就可以了。估计是因为<>括号是非法字符。
另外我看到你代码里面，train的时候，是把句子逆序放进model里面的吗？按照逆序来train的？

**Comment by JustinLin610** [comment]
> > 把更新了的代码里面的RELEASE-1.5.5放到home下然后再set rouge path，或者直接修改对它的权限，这样pyrouge的使用应该就没有问题。division by zero一般的情况是有空行或者是非法字符
> 
> Illegal division by zero at /root/RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450
> 我这个问题是因为有非法字符，我把utils/metrics.py里面的第49行后面加上.replace('', 'UNK')就可以了。估计是因为<>括号是非法字符。
> 另外我看到你代码里面，train的时候，是把句子逆序放进model里面的吗？按照逆序来train的？

对，这个是以前用单向的时候参考Stanford那边的经验改成逆序，现在用双向就不考虑这个问题了。

**Comment by jiahuanluo** [comment]
> > > 把更新了的代码里面的RELEASE-1.5.5放到home下然后再set rouge path，或者直接修改对它的权限，这样pyrouge的使用应该就没有问题。division by zero一般的情况是有空行或者是非法字符
> > 
> > 
> > Illegal division by zero at /root/RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450
> > 我这个问题是因为有非法字符，我把utils/metrics.py里面的第49行后面加上.replace('', 'UNK')就可以了。估计是因为<>括号是非法字符。
> > 另外我看到你代码里面，train的时候，是把句子逆序放进model里面的吗？按照逆序来train的？
> 
> 对，这个是以前用单向的时候参考Stanford那边的经验改成逆序，现在用双向就不考虑这个问题了。

谢谢大佬~
